[tool.poetry]
name = "laughbot3000"
version = "0.1.0"
description = "Dependencies for a fun project"
authors = ["Diego Pardo"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
